// src/utils/solicitudesData.js

export const solicitudes = [
  {
    "id": 1,
    "nombre": "Juan Carlos Ramirez Lopez",
    "email": "juan.ramirez@email.com",
    "telefono": "961456789",
    "escuela": "FCA",
    "tipo": "Pueblo",
    "areaTrabajo": "Planta Fisica",
    "date": "2024-09-01",
    "destination": "Pueblo Nuevo",
    "description": "Compras al pueblo",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 2,
    "nombre": "Pedro Fernandez Garcia",
    "email": "pedro.fernandez@email.com",
    "telefono": "961456789",
    "escuela": "CIED",
    "tipo": "Especial",
    "areaTrabajo": "Biblioteca",
    "date": "2024-09-05",
    "destination": "Tuxtla Gutierrez",
    "description": "Cita Acta Documentacion RFC",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 3,
    "nombre": "Alberto Rodriguez Martinez",
    "email": "alberto.rodriguez@email.com",
    "telefono": "961456789",
    "escuela": "FacPsy",
    "tipo": "Especial",
    "areaTrabajo": "Comedor",
    "date": "2024-09-10",
    "destination": "Guerrero",
    "description": "Cita con el Dr. para operacion",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 4,
    "nombre": "Maria Gonzalez Hernandez",
    "email": "maria.gonzalez@email.com",
    "telefono": "961456789",
    "escuela": "IDS",
    "tipo": "A Casa",
    "areaTrabajo": "Costura",
    "date": "2024-09-15",
    "destination": "San Cristobal de las Casas",
    "description": "Visita Familiar",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 5,
    "nombre": "Luis Perez Rodriguez",
    "email": "luis.perez@email.com",
    "telefono": "961456789",
    "escuela": "FT",
    "tipo": "Especial",
    "areaTrabajo": "Carreton",
    "date": "2024-09-20",
    "destination": "Hospital General",
    "description": "Consulta Medica",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 6,
    "nombre": "Ana Garcia Lopez",
    "email": "ana.garcia@email.com",
    "telefono": "961456789",
    "escuela": "LEMyS",
    "tipo": "A Casa",
    "areaTrabajo": "Sistemas",
    "date": "2024-09-25",
    "destination": "Comitan de Dominguez",
    "description": "Reunion Familiar",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 7,
    "nombre": "Javier Martinez Hernandez",
    "email": "javier.martinez@email.com",
    "telefono": "961456789",
    "escuela": "FCA",
    "tipo": "Especial",
    "areaTrabajo": "Vida util",
    "date": "2024-09-30",
    "destination": "Aeropuerto",
    "description": "Viaje de Emergencia",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 8,
    "nombre": "Sofia Sanchez Rodriguez",
    "email": "sofia.sanchez@email.com",
    "telefono": "961456789",
    "escuela": "CIED",
    "tipo": "Pueblo",
    "areaTrabajo": "Monitoria",
    "date": "2024-10-05",
    "destination": "Pueblo Nuevo",
    "description": "Compra de Artesanias",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 9,
    "nombre": "Miguel Hernandez Garcia",
    "email": "miguel.hernandez@email.com",
    "telefono": "961456789",
    "escuela": "FacPsy",
    "tipo": "Especial",
    "areaTrabajo": "Papeleria",
    "date": "2024-10-10",
    "destination": "Clinica Dental",
    "description": "Consulta Odontologica",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 10,
    "nombre": "Laura Perez Lopez",
    "email": "laura.perez@email.com",
    "telefono": "961456789",
    "escuela": "IDS",
    "tipo": "A Casa",
    "areaTrabajo": "VRA",
    "date": "2024-10-15",
    "destination": "Palenque",
    "description": "Visita Padres",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 11,
    "nombre": "Daniel Garcia Rodriguez",
    "email": "daniel.garcia@email.com",
    "telefono": "961456789",
    "escuela": "FT",
    "tipo": "Pueblo",
    "areaTrabajo": "VRE",
    "date": "2024-10-20",
    "destination": "Pueblo Nuevo",
    "description": "Compra de Productos Personales",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 12,
    "nombre": "Isabel Rodriguez Hernandez",
    "email": "isabel.rodriguez@email.com",
    "telefono": "961456789",
    "escuela": "LEMyS",
    "tipo": "Especial",
    "areaTrabajo": "Limpieza",
    "date": "2024-10-25",
    "destination": "Cita Documentacion",
    "description": "cita en la torre documentacion pdte",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 13,
    "nombre": "Alejandro Hernandez Garcia",
    "email": "alejandro.hernandez@email.com",
    "telefono": "961456789",
    "escuela": "FCA",
    "tipo": "A Casa",
    "areaTrabajo": "Marketing",
    "date": "2024-10-30",
    "destination": "Tuxtla Gutierrez",
    "description": "Reunion de familia",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 14,
    "nombre": "Carmen Garcia Lopez",
    "email": "carmen.garcia@email.com",
    "telefono": "961456789",
    "escuela": "CIED",
    "tipo": "Pueblo",
    "areaTrabajo": "Gema",
    "date": "2024-11-05",
    "destination": "Pueblo Nuevo",
    "description": "Compra de Ropa Tradicional",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 15,
    "nombre": "Jose Rodriguez Hernandez",
    "email": "jose.rodriguez@email.com",
    "telefono": "961456789",
    "escuela": "FacPsy",
    "tipo": "Especial",
    "areaTrabajo": "Planta Fisica",
    "date": "2024-11-10",
    "destination": "Sinaloa",
    "description": "Viaje compromiso",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 16,
    "nombre": "Elena Hernandez Garcia",
    "email": "elena.hernandez@email.com",
    "telefono": "961456789",
    "escuela": "IDS",
    "tipo": "A Casa",
    "areaTrabajo": "Biblioteca",
    "date": "2024-11-15",
    "destination": "Comitan de Dominguez",
    "description": "Personal",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 17,
    "nombre": "Ricardo Garcia Lopez",
    "email": "ricardo.garcia@email.com",
    "telefono": "961456789",
    "escuela": "FT",
    "tipo": "Pueblo",
    "areaTrabajo": "Comedor",
    "date": "2024-11-20",
    "destination": "Pueblo Nuevo",
    "description": "Compra de Cafe",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 18,
    "nombre": "Veronica Hernandez Garcia",
    "email": "veronica.hernandez@email.com",
    "telefono": "961456789",
    "escuela": "LEMyS",
    "tipo": "Especial",
    "areaTrabajo": "Costura",
    "date": "2024-11-25",
    "destination": "Hospital General",
    "description": "Visita a Paciente",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  },
  {
    "id": 19,
    "nombre": "Manuel Garcia Lopez",
    "email": "manuel.garcia@email.com",
    "telefono": "961456789",
    "escuela": "FCA",
    "tipo": "A Casa",
    "areaTrabajo": "Carreton",
    "date": "2024-11-30",
    "destination": "Tuxpan Veracruz",
    "description": "Cita con Notario",
    "documentos": "Documentos adjuntados",
    "estatus": "Pendiente",
  },
  {
    "id": 20,
    "nombre": "Patricia Hernandez Garcia",
    "email": "patricia.hernandez@email.com",
    "telefono": "961456789",
    "escuela": "CIED",
    "tipo": "Pueblo",
    "areaTrabajo": "Sistemas",
    "date": "2024-12-05",
    "destination": "Pueblo Nuevo",
    "description": "Compra de ropa",
    "documentos": "Documentos adjuntados",
    "estatus": "Aprobada",
  }
];
